### ISSUE TITLE
Versioning docs fails

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows-samples#408]
```
PS C:\Users\nickg\Desktop\react-native-windows-samples\website> yarn version 0.64
yarn version v1.22.0
error Use the "--new-version [version]" flag to create a new version.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
```

```
PS C:\Users\nickg\Desktop\react-native-windows-samples\website> yarn version --new-version 0.64
yarn version v1.22.0
error Invalid version supplied.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
```

```
PS C:\Users\nickg\Desktop\react-native-windows-samples\website> yarn version --new-version 0.64.0
yarn version v1.22.0
info New version: 0.64.0
$ docusaurus-version
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
C:\Users\nickg\Desktop\react-native-windows-samples\website\node_modules\docusaurus\lib\version.js:59
if (version.includes('/')) {
            ^

TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (C:\Users\nickg\Desktop\react-native-windows-samples\website\node_modules\docusaurus\lib\version.js:59:13)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
PS C:\Users\nickg\Desktop\react-native-windows-samples\website>
```

**Comment by NickGerleman** [comment]
User error here. `yarn version` does something special compared to `yarn run version`.
